### PR TITLE
Update jp.m3u

### PR DESCRIPTION
**Pull request by weldon1045**
- Fix missing EPG for Osaka channels.
- Changing CNN US to CNNj upon live verification with an online TV Guide.

### CODE REVIEW

**Comment by weldon1045** [comment]
If they accept to add the channels left, I might resubmit this as a full merge with a new EPG provider.
https://github.com/Animenosekai/japanterebi-xmltv/issues/1

**Comment by weldon1045** [comment]
Branch has been renamed as patch-2. This PR will be resubmitted once the issue mentioned before is resolved.

**Comment by luongz** [comment]
> If they accept to add the channels left, I might resubmit this as a full merge with a new EPG provider. [Animenosekai/japanterebi-xmltv#1](https://github.com/Animenosekai/japanterebi-xmltv/issues/1)

JCOM EPG doesn't have Tokyo MX2, it's impossible to add it
And the CNN channel in the list is CNN US, not CNN J (needs to be confirmed)

I think just need to wait for my host to be fixed. My script uses Bangumi epg, which contains most of all JP channels.

**Comment by weldon1045** [comment]
Talking about that, I've noticed before the host broke that sometimes, EPG would be empty for some channels in some days. In the particular case of the Osaka Channels, it would be avaliable for some days, then be empty on other days, and this happened with some other channels as well.

Apart from the necessary EPG info fix, idk if the issue I mentioned will be covered as well.

**Comment by Animenosekai** [comment]
It's annoying that `iptv-org` uses weird IDs for the channels like `JOOYDTV.jp` instead of `MBS`

**Comment by weldon1045** [comment]
I have a great idea, how about @luongz modifying the script so the TVG IDs match Anise/IPTV-org IDs, then, Anise source is added as a backup in case yours is not avaliable.

**Comment by luongz** [comment]
> I have a great idea, how about @luongz modifying the script so the TVG IDs match Anise/IPTV-org IDs, then, Anise source is added as a backup in case yours is not avaliable.

Tbh i don't like the iptv-org channels id format. My EPG grabber is not the iptv-org one.

**Comment by weldon1045** [comment]
In regards to CNN, the channel is currently CNNj. Right now they are on a program about environment, while CNN US is on News Room.

Check here:
https://tvguide.myjcom.jp/?channelType=120&date=20240728

**Comment by Animenosekai** [comment]
> Tbh i don't like the iptv-org channels id format.

Me too lmao

**Pull request closed without merging**
